### ISSUE TITLE
Rusty RPTerminal

### ISSUE THREAD

**Issue by sanam2405** [sanam2405/rp#31]
The current **`RPTerminal`** shipped with the desktop application is non-functional. This is simply because the web-socket backend logic to handle the terminal sessions and spawning pseudo-terminals was handled by **`apps/api`**  _**Node.js**_ code. This is currently not being shipped with the desktop app. 

The current RPTerminal is accessible only on the web application at `/rterm`. I need to create a native **websocket terminal handler in Rust** to ship it with the cross-platform desktop application too.

**To-Do**

- [ ] create a pty handler in Rust to handle terminal connections
- [ ] setup a bi-lateral communication channel 
- [ ] execute the terminal commands as child-processes

## Alternatives to writing a native rust-pty handler

<img width="735" alt="Screenshot 2024-12-15 at 3 05 38 PM" src="https://github.com/user-attachments/assets/5788a857-be5d-421f-b26f-f42b54fda8d4" />

- **Bundle Node.js with the Tauri App**
To package Node.js with the Tauri app, I can use tools like pkg or nexe to bundle the Node.js runtime and the Express server into a single executable.
- **Use Node.js as a Dependency**
If I prefer to ship Node.js alongside the Tauri app, I can include the Node.js runtime as part of the app distribution.

## Performance
<img width="755" alt="Screenshot 2024-12-15 at 2 58 12 PM" src="https://github.com/user-attachments/assets/0ef741f4-d649-4133-8cbc-9a44d01ee02b" />

[**Playlist**](https://open.spotify.com/playlist/5VOcst0tGcSUNi8QInDcPX)

[![](https://github.com/user-attachments/assets/e14cb78e-47cd-4011-8b10-07c68370241e)](https://open.spotify.com/playlist/5VOcst0tGcSUNi8QInDcPX)
